### ISSUE TITLE
使用模型爆显存

### ISSUE THREAD

**Issue by dongteng** [WENGSYX/Deberta-Chinese#3]
请问大佬，V100 32GB 会爆显存 。其它模型如roberta-large就没有这种情况，调低batchsize到4都爆，请问是什么原因呢？多有打扰！

**Comment by WENGSYX** [comment]
是不是没开fp16？或者maxlen太大？
实在不行，就换个模型？我推荐你用这个->https://github.com/WENGSYX/CirBERTa

**Comment by dongteng** [comment]
好的 多谢您



------------------&nbsp;Original&nbsp;------------------
From: "Yixuan ***@***.***&gt;; 
Date: 2022年4月17日(星期天) 晚上11:14
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [WENGSYX/Deberta-Chinese] 使用模型爆显存 (Issue #3)





 
是不是没开fp16？或者maxlen太大？
 实在不行，就换个模型？我推荐你用这个-&gt;https://github.com/WENGSYX/CirBERTa
